### ISSUE TITLE
cat_client 执行的错误

### ISSUE THREAD

**Issue by Yoop-yes** [TryGOTry/CobaltStrike_Cat_4.5#18]
cat_client 执行 sudo java -jar cat_client.jar
提示 usage: [client|version]

cat_client 执行 sudo java -jar cat_client.jar client
提示[!] client (1.1.1.1) read [TeamQueue Reader]: null

at_server在ubuntu中执行 cat_client链接是提示
[-] client (1.1.1.1) read [Manage: neo]: No location for 'e_lfanew'
java.lang.IllegalArgumentException: No location for 'e_lfanew'
	at pe.PEParser.getLocation(Unknown Source)
	at pe.PEEditor.setValueAt(Unknown Source)
	at pe.PEEditor.removeRichHeader(Unknown Source)
	at pe.PEEditor.insertRichHeader(Unknown Source)
	at pe.MalleablePE.pre_process(Unknown Source)
	at c2profile.Preview.getPE(Unknown Source)
	at c2profile.Preview.summarize(Unknown Source)
	at server.ManageUser.process(ManageUser.java:117)
	at server.ManageUser.run(ManageUser.java:210)
	at java.base/java.lang.Thread.run(Thread.java:829)
是我操作不对还是什么

**Comment by TryGOTry** [comment]
检查服务端profile文件。
尝试使用自带profile文件是否正常。

**Comment by Yoop-yes** [comment]
默认的可以执行了，谢谢咯，大佬，我在检查检查profile文件
