### ISSUE TITLE
client 1.1.1.1?

### ISSUE THREAD

**Issue by Ro0tTjng** [TryGOTry/CobaltStrike_Cat_4.5#19]
[-] client (1.1.1.1) read [main]: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
        at java.base/javax.net.ssl.DefaultSSLServerSocketFactory.throwException(SSLServerSocketFactory.java:177)
        at java.base/javax.net.ssl.DefaultSSLServerSocketFactory.createServerSocket(SSLServerSocketFactory.java:205)
        at ssl.SecureServerSocket.<init>(SecureServerSocket.java:168)
        at server.TeamServer.B(TeamServer.java:67)
        at ServerMain.main(ServerMain.java:33)
        at Cobaltstrike.main(Cobaltstrike.java:26)
Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
        at java.base/java.security.Provider$Service.newInstance(Provider.java:1868)
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:185)
        at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:110)
        at java.base/javax.net.ssl.SSLServerSocketFactory.getDefault(SSLServerSocketFactory.java:74)
        at ssl.SecureServerSocket.A(SecureServerSocket.java:174)
        at ssl.SecureServerSocket.<init>(SecureServerSocket.java:167)
        ... 3 more
Caused by: java.security.KeyManagementException: keystore password was incorrect
        at java.base/sun.security.ssl.SSLContextImpl$DefaultManagersHolder.<clinit>(SSLContextImpl.java:942)
        at java.base/sun.security.ssl.SSLContextImpl$DefaultSSLContext.<init>(SSLContextImpl.java:1111)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at java.base/java.security.Provider$Service.newInstanceOf(Provider.java:1879)
        at java.base/java.security.Provider$Service.newInstanceUtil(Provider.java:1886)
        at java.base/java.security.Provider$Service.newInstance(Provider.java:1861)
        ... 10 more

**Comment by TryGOTry** [comment]
cobaltstrike.store    password was incorrect

**Comment by TryGOTry** [comment]
看不懂报错吗

**Comment by Ro0tTjng** [comment]
> 可以了
