### ISSUE TITLE
443端口长期开启后，关闭并报错

### ISSUE THREAD

**Issue by g543fdg** [TryGOTry/CobaltStrike_Cat_4.5#23]
具体报错信息如下：
[19137.959s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[19137.960s][warning][os,thread] Failed to start the native thread for java.lang.Thread "HTTP session handler"
Exception in thread "Web Server on port 443" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
        at java.base/java.lang.Thread.start0(Native Method)
        at java.base/java.lang.Thread.start(Thread.java:798)
        at cloudstrike.NanoHTTPD$HTTPSession.<init>(NanoHTTPD.java:239)
        at cloudstrike.NanoHTTPD$1.run(NanoHTTPD.java:189)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by TryGOTry** [comment]
没遇到过这种问题。开了几个月也没事

**Comment by g543fdg** [comment]
CatClient.properties是否为默认配置呢

**Comment by TryGOTry** [comment]
和这些配置无关吧。要不你本地先挂几天试试吧
